### ISSUE TITLE
v0.5.12 Writing blank files, no exeption thrown

### ISSUE THREAD

**Issue by VarSell** [Mbucari/AAXClean#11]
Hi! I was rewriting my old project, and updated AaxClean to 0.5.12, but am facing issues with this new version.
I've ensured the activation bytes are correct. All it does is write a blank file, not throwing any exceptions.
I'm not sure if I should include any other information, please let me know if so.
Attached is the written file, renamed to .log, along with the example code tried.
[outFile.mb4.log](https://github.com/Mbucari/AAXClean/files/10505690/outFile.mb4.log)
```
AaxFile encryptedFile = new AaxFile(File.OpenRead(@"cmage.aax"));
encryptedFile.SetDecryptionKey("1613711c");
_=encryptedFile.ConvertToMp4aAsync(File.OpenWrite(@"outFile.m4b"));
```

**Comment by Mbucari** [comment]
Unfortunately I don't think I have any aax files anymore. Would you mind sharing one of the problem files?

**Comment by VarSell** [comment]
Thanks for the response 👍  Here is the same file I was using. [Mega - Combat Mage](https://mega.nz/file/MRJC3BTS#qdswCzkMK2_-MdpBj2Kc-A5RPx8qS14ngXJcAxyZRc8) Bytes: 1613711c
I hope I wasn't doing anything stupid with the library aha. I wanted to rewrite some old code as it was pretty embaressing, but I might just get a lifetime's worth if I was overlooking something obvious 😹

**Comment by Mbucari** [comment]
The problem is that I got rid is the synchronous conversion methods. All conversions are async-only, and you are not awaiting the conversion.

If you're calling ConvertToMp4aAsync from an async method, do it like this:
```C#
await encryptedFile.ConvertToMp4aAsync(File.OpenWrite(@"outFile.m4b"));
```

If you're not in an async method, you need to call the async method synchronously like this:

```C#
encryptedFile.ConvertToMp4aAsync(File.OpenWrite(@"outFile.m4b")).GetAwaiter().GetResult();
```

**Comment by VarSell** [comment]
Oh, I'm so sorry, that's a rather stupid mistake. Thanks for pointing it out, worked perfectly. I was calling the async method without awaiting it, and forgot to use GetAwaiter() when using synchronous. Thanks!
