### ISSUE TITLE
How to remove tags?

### ISSUE THREAD

**Issue by shelltar** [Mbucari/AAXClean#12]
As in title, I've been looking for a way to remove certain tags from my audiobook files, but with this tool I only managed to make them empty. I want to remove the whole field, not just set it to an empty value.

**Comment by Mbucari** [comment]
It's pretty straight-forward. Here's an sample that removes all tags from an mp4 file then saves it.

```C#
var input = File.Open(@"file.mp4", FileMode.Open, FileAccess.ReadWrite);
var mp4 = new Mp4File(input);

foreach (var tag in mp4.AppleTags.AppleListBox.Tags.ToList())
  mp4.AppleTags.AppleListBox.Children.Remove(tag);

await mp4.SaveAsync();
```

**Comment by shelltar** [comment]
Thank you, that's what I was looking for. I don't know if it could be done better, but it works :)

```
using (var inputFileStream = File.Open(Path.Combine(folderPath, $"{fileNameWithoutExtension}.{decryptedExtension}"), FileMode.Open, FileAccess.ReadWrite))
{
   var inputMp4File = new Mp4File(inputFileStream);
   var tagsToRemove = new[] { "©des", "AACR", "prID", "CDEK", "CDET", "VERS", "@sti" };
   inputMp4File.AppleTags.AppleListBox.Children.RemoveAll(t => tagsToRemove.Contains(t.Header.Type));
   await inputMp4File.SaveAsync();
}
```

**Comment by Mbucari** [comment]
Looks good to me. Note that if you remove tags from the aax file before converting, all changes are saved to the converted file. So you don't have to convert, open, edit, then save.
