### ISSUE TITLE
Silence Detection is slow.

### ISSUE THREAD

**Issue by Mbucari** [Mbucari/AAXClean#3]
This seems to be the only issue at the moment, so I'm making it a new issue. @audiamus

**Comment by Mbucari** [comment]
I'm working on an aac decoding library based on FFmpeg. It uses the bare essentials from the FFmpeg library and the lib size is about 2 MB.  Unfortunately, the decoded audio has a terrible hiss and I'm not sure why.

**Comment by audiamus** [comment]
There's absolutely no hurry from my side.

**Comment by Mbucari** [comment]
Fixed this with latest update and new project [AAXClean.Codecs](https://github.com/Mbucari/AAXClean.Codecs)

Silence detect is faster than ffmpeg now, but it does require SSE2 cpu capability. Shouldn't be a problem these days.
