### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jaan143** [Mbucari/AAXClean#4]
hello Dear
can you please make windows Gui for me ?
i dont know about programming but i want to use that to convert in mp3

thank you so much

**Comment by JKamsker** [comment]
Just use one of those: https://github.com/rmcrackan/AudiobookHub#backup-decrypt-convert-organize

**Comment by Mbucari** [comment]
@jaan143 This project is intended to be used as a library by other applications. It's used in [Libation](https://github.com/rmcrackan/Libation) which is a great project you should look at if you're interested in backing up your whole library.
