### ISSUE TITLE
Feature request: CLI interface

### ISSUE THREAD

**Issue by mkb79** [Mbucari/AAXClean#5]
@Mbucari Respect to your work. 

Is it possible to create a CLI binary of `AAXClean` which I can bundle with my `audible-cli` package?

Best regards

**Comment by Mbucari** [comment]
I can do that, with a caveat. The MP3 encoder and silence detection are windows-only, and I have no plan to make it cross-platform. They rely on a native aac decoder which is windows-only.  I can make a CLI tool to take an aax or aaxc input file and decrypt it to a m4b file (single file or split into multiple files), because all that code is C# and cross platform. 

Also, I don't have experience published to Linux or Mac. Do you need only a windows .exe, or would you need other platforms?

**Comment by mkb79** [comment]
Linux support is important for me. In addition to `audible-cli` I would implement `AAXClean` in my `MyAudible` repo. `MyAudible` will run in a docker container, when it is ready.

AAXClean should run under the following environment:

- 64 bit Linux support (run in docker)
- standalone binary
- decrypt aax and aaxc on-the-fly without reencoding (while downloading the encrypted file run decryption on downloaded parts)
- preserve all metadata

This would be very fantastic for me!

**Comment by Mbucari** [comment]
> decrypt aax and aaxc on-the-fly without reencoding (while downloading the encrypted file run decryption on downloaded parts)

How do you expect that to work? Do you want to pipe aax(c) files to aaxclean-cli stdin? Or maybe pass the aax(c) file url to aaxclean-cli and let it download/decrypt on the fly?

**Comment by mkb79** [comment]
I suggest the 2nd way. I thought of the following:

1. A client communicate with a HTTP-Webserver which runs MyAudible and AAXClean. 
2. The client wishes to download an audio file instead of streaming 
3. The webserver makes the licenserequest to the Audible API
4. AAXClean downloads the file and pipes the output via http stream to the client.

**Comment by Mbucari** [comment]
So in step #4, aaxclean-cli would pipe decrypted mpeg4 to stdout, and your app will read and redirect the output to http? That sounds like a good plan, but it has some challenges. 

Currently, AAXClean's output stream must be seekable. In order to write the entire decrypted m4b sequentially without seeking, I'll need to pre-calculate the final size.  That is easy to do if all you need is a single mpeg4 file (not split). But if you want the option to split the output into multiple files, it would be a lot more complicated (and not something I'm prepared to do).

Also, do you want/need the ability to specify different chapter markers from the ones that are embedded in the aax file?  AAXClean supports this.

**Comment by audiamus** [comment]
> Also, I don't have experience published to Linux or Mac

Publishing should work out of the box. (I'm using this often enough for Linux in my professional work.) This is really great about .Net Core/5 nowadays.

You can test it on Win 10 with WSL and Ubuntu. Which also allows interactive debugging with Visual Studio.

**Comment by mkb79** [comment]
@Mbucari  MyAudible can (when ready) run via docker on everyones 64bit PC or NAS (like my Synology). To not waste to much hard drive space the client can decide to instant download the file (not split) or to store it on the MyAudible machine (and maybe later as a feature to split the file)!

**Comment by rmcrackan** [comment]
Am I correct that the conversion portion of Libation will always be Windows-only? (This is not a criticism -- it was strictly Windows-only before AAXClean also.) I'm updating my enhancement list and I can eliminate x-platform as a possible future enhancement if it isn't in the cards.

**Comment by Mbucari** [comment]
Probably, unless I can make a .NET aac decoder. I had started, but it's convoluted as hell so I never finished.  Also, even if I'm successful it could be just too slow. I've played with three decoders made by 3 separate outfits, and the one in ffmpeg is by far the fastest. But damn, it's complicated.  I'd only need to implement the LC subset of the standard, but it's still a big undertaking.

**Comment by rmcrackan** [comment]
Have you considered using something like [this](https://ffmpeg.xabe.net/) as a band aid for those parts?

**Comment by Mbucari** [comment]
Yes, very briefly, and discarded it almost immediately.  It requires ffmpeg libraries as dependencies, so you're back up to >60MB per platform in dependencies.  It goes against my philosophy of this project.

**Comment by Mbucari** [comment]
FYI, my idea going forward is to remove mp3 conversion from AAXClean. I would like AAXClean to either:

1. Decrypt to an mpeg-4 stream.
2. Decrypt to aac.
3. Decrypt to an raw wave stream.

Then, the user can re-encode the wave stream into whatever format they want. I'd like to get out of supporting mp3 and let users handle that themselves.

**Comment by audiamus** [comment]
> I'd like to get out of supporting mp3 and let users handle that themselves.

Excellent idea. If I understand correctly, that would remove platform dependency and allow "any CPU" apps.

**Comment by rmcrackan** [comment]
> Excellent idea

Speak for yourself :wink: Libation is using AAXClean for all audio conversions.

Kidding aside, I understand. I'm just not looking forward to integrating a new mp3 library lest I have to drop features.

**Comment by Mbucari** [comment]
> that would remove platform dependency and allow "any CPU" apps.

Yes, IF I drop the aac decoder or make it into a different package. That would allow AAXClean to be platform and architecture independent It's a goal I'm working towards.  As to the timeline for all of this, probably not until after the new year. Work is extremely hectic right now.

> I'm just not looking forward to integrating a new mp3 library lest I have to drop features.

I won't leave you hanging! I'm thinking about spinning off some of this functionality into a separate project that would be windows only. But even if I don't, the package AAXClean uses (https://github.com/Corey-M/NAudio.Lame) is easy to use with a raw wave stream.

**Comment by rmcrackan** [comment]
Muchas gracias!

**Comment by Mbucari** [comment]
I'm getting around to this.  I just finished a lot of the heady lifting by making AAXClean ANY CUP and platform independent.

**Comment by Mbucari** [comment]
I've mad an alpha cli tool.  It's platform independent, and I have bins for win 32/64, linux64 and osx64.

https://github.com/Mbucari/aaxclean-cli/releases/tag/0.1.0
