### ISSUE TITLE
Hi, I'm a regular Windows user...how do I install & use this?

### ISSUE THREAD

**Issue by paulescobar** [Mbucari/AAXClean#6]
I love the idea behind your program. But I don't understand the "ReadMe" documentation.

Like I'm able to install something like youtube-dl that doesn't have a GUI and runs off command line.

But I've never seen anything like the style of commands that's shown in the readme. 

Any chance we could get a more newb friendly release of your program?

**Comment by VarSell** [comment]
@paulescobar It's not meant to be a command line program. It's a library to be used by other programs, not by itself.
There are plenty of other user friendly CLI and GUI decrypters out there though.
