### ISSUE TITLE
 Decryption results in partially invalid file

### ISSUE THREAD

**Issue by JKamsker** [Mbucari/AAXClean#8]
Happens for me with this audiobook: https://www.audible.de/pd/Alle-diese-Welten-Hoerbuch/3837146618

Playing it with vlc works seemlessly, but when opening with ffmpeg, it echos out this errors: 
![image](https://user-images.githubusercontent.com/11245306/149038456-c342babd-7cf4-4434-8039-1fd997367f98.png)
![image](https://user-images.githubusercontent.com/11245306/149038471-8900fb7d-1264-4049-8b22-73bffbfba406.png)

Converting the file with ffmpeg results in the first error not appearing.

This error makes it impossible to use the audiobook with [AudioBookShelf](https://github.com/advplyr/audiobookshelf). Streaming atleast, because it encodes it with hls while streaming with this command:
```bash
ffmpeg -seek_timestamp 1 -f concat -safe 0 -i audiobook.m4b -y -map 0:a -c:a copy -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename out/output-%d.ts out/final-output.m3u8
```
It crashes with 
![image](https://user-images.githubusercontent.com/11245306/149038917-3e7d2827-9af5-4ec6-bc4a-cf49abadf045.png)

**Comment by Mbucari** [comment]
I ran into this bug a while ago.  I believe it's an error in ffmpeg's parsing of the AudioSpecificConfig info. This error was part of the reason I made AAXClean.  It doesn't have this problem.
