### ISSUE TITLE
Messed-up meta data

### ISSUE THREAD

**Issue by audiamus** [Mbucari/AAXClean#9]
After many weeks of more or less intensive development, I released a first version of my own Audible client a week ago. I called it [Book Lib Connect](https://github.com/audiamus/BookLibConnect). Originally I wanted to integrate download functionality into AAX Audio Converter right from the beginning, but then decided against it and to publish the downloader as a stand-alone app first.

Among a number of reported issues with the new app, one appears to be targeting AAXClean.

It seems that AAXClean might muddle the embedded chapter data. Book Lib Connect uses AAXClean in "no-frills" mode, Single aaxc in, Single m4b out, No external chapter arguments. embedded chapters only.  

In https://github.com/audiamus/BookLibConnect/issues/3 a user reported - after solving the original issue of hierarchical chapter data in the Audible server json response - that the book did not convert to MP3 in full, using AAX Audio Converter. It has 78 chapters but was cut short after 66. AAX Audio Converter delegates conversion to FFmpeg as I mentioned before. To track it down, I substituted FFmpeg with the latest release and the problem was gone. So, for the moment, we have a workaround. However, I became curious that the real course might be something different. I asked the user to inspect both the .aaxc (as downloaded) and the .m4b file (as decrypted by AAXClean) with MediaInfo. And there is a big difference: the chapter order. In the m4b file it is incorrect, starting near the end of the book and continuing with the earlier chapters further down, and chapter time offsets all wrong for that range. 

I attach the user's MediaInfo findings:
[Mediainfo.Todesreigen.AAXC.plus.m4b.zip](https://github.com/Mbucari/AAXClean/files/7925575/Mediainfo.Todesreigen.AAXC.plus.m4b.zip)

**Comment by audiamus** [comment]
This appears to be related: #7

**Comment by audiamus** [comment]
It is related indeed and the patch in #7 fixes it. :smiley:

**Comment by Mbucari** [comment]
I am SO sorry I've been ignoring this problem.  I've been super busy and haven't even opened this project since November.  I added the fix along with a whole lot of other new stuff.
